wikipedia_transforms:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: cloud-portfolio-project-495513
      dataset: wikipedia_marts
      location: europe-west1
      threads: 1
      keyfile: /tmp/credentials.json